language: minimal

branches:
  only:
    - develop
    - master
    - /^release\/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  include:
    # build and test
    - stage: first stage
      name: first step
      script:
        - sleep 10

    - stage: first stage
      name: second step
      script:
        - sleep 10

    - stage: first stage
      name: third step
      script:
        - sleep 10

notifications:
  email:
    on_success: never
    on_failure: always
